import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { profile, sections } from "@/content/profile";
import { SITE_DESCRIPTION, SITE_KEYWORDS, SITE_NAME, SITE_URL } from "@/lib/site";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase resolves every relative URL below (canonical, OG images) into
  // an absolute one. Without it Next warns and OG images silently don't work.
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${profile.name} — ${profile.role}`,
    template: `%s | ${profile.name}`,
  },
  description: SITE_DESCRIPTION,
  keywords: SITE_KEYWORDS,
  authors: [{ name: profile.name, url: SITE_URL }],
  creator: profile.name,
  publisher: profile.name,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "profile",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${profile.name} — ${profile.role}`,
    description: SITE_DESCRIPTION,
    locale: "en_US",
    // The image itself is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: `${profile.name} — ${profile.role}`,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "technology",
};

export const viewport = {
  themeColor: "#08090b",
  colorScheme: "dark" as const,
};

/**
 * JSON-LD Person schema.
 *
 * Gives search engines an unambiguous, structured description of who this page
 * is about — employer, alumniOf, and sameAs profiles — instead of inferring it
 * from prose. Built from the same content layer the page renders, so it cannot
 * drift out of sync with what is displayed.
 */
function PersonJsonLd() {
  const current = profile.contact.links
    .filter((link) => link.external || link.href.startsWith("mailto:"))
    .map((link) => link.href);

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: profile.name,
    jobTitle: profile.role,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    email: `mailto:${profile.contact.email}`,
    telephone: profile.contact.phone,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Hyderabad",
      addressCountry: "IN",
    },
    worksFor: {
      "@type": "Organization",
      name: "Bridgera",
    },
    alumniOf: {
      "@type": "CollegeOrUniversity",
      name: "International Institute of Information Technology, Hyderabad",
    },
    knowsAbout: [
      "Backend Engineering",
      "Distributed Systems",
      "AWS",
      "Event-Driven Architecture",
      "Retrieval-Augmented Generation",
      "Federated Learning",
    ],
    sameAs: current,
    hasPart: sections.map((section) => ({
      "@type": "WebPageElement",
      name: section.label,
      url: `${SITE_URL}/#${section.id}`,
    })),
  };

  return (
    <script
      type="application/ld+json"
      // Content is authored locally, not user input; escaping the closing tag
      // sequence is what actually matters for safe inline JSON.
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
      }}
    />
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen bg-canvas font-sans text-ink antialiased">
        {/* Keyboard users can jump past the navigation straight to content. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded focus:bg-accent focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-white"
        >
          Skip to content
        </a>
        <Navbar />
        {children}
        <Footer />
        <PersonJsonLd />
      </body>
    </html>
  );
}
